name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: assets/static/package.json
      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: assets/static/.nvmrc
          cache: pnpm
          cache-dependency-path: assets/static/pnpm-lock.yaml
      - name: Go generate
        run: go generate -x
      - name: Test
        run: go test ./...

  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: assets/static/package.json
      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: assets/static/.nvmrc
          cache: pnpm
          cache-dependency-path: assets/static/pnpm-lock.yaml
      - name: Set build variables
        id: vars
        run: |
          args='release --clean'
          if [[ "$GITHUB_REF" != refs/tags/* || "$GITHUB_REF_NAME" != v*.*.* ]]; then
            args+=' --snapshot'
          fi
          echo "args=$args" >> $GITHUB_OUTPUT
      - name: Generate Token
        id: app-token
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          repositories: linx-server,homebrew-tap
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          version: v2
          args: ${{ steps.vars.outputs.args }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
      - name: Push beta image
        if: github.ref_name == 'main'
        run: |
          export REPO="$(tr '[[:upper:]]' '[[:lower:]]' <<< "ghcr.io/$GITHUB_REPOSITORY")"
          IMAGES=()
          while read -r SOURCE DEST; do
            docker tag "$SOURCE" "$DEST"
            docker push "$DEST"
            IMAGES+=("$DEST")
          done \
            < <(docker image ls --format=json | \
              yq --input-format=json --output-format=tsv '
                select(.Repository == strenv(REPO)) |
                [
                  .Repository + ":" + .Tag,
                  .Repository + ":beta-" + (.Tag | sub(".*-", ""))
                ]
              ')

          docker manifest create "$REPO:beta" "${IMAGES[@]}"
          docker manifest push "$REPO:beta"
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: dist
          path: dist
